typography_spectrum: 0.3637826421763748
color:
  saturation: 0.7120652911253273
  lightness: 0.49117944901809096
  brandStrength: 0.01527991727925837
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
  rhythmicContrast: 0.42171172657981515
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.911001629428938
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Christian Thanninger
  email: admin@thanninger.de
name: Thanninger
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Thanninger
purpose: []
