title: Thanninger
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3920009802095592
  lightness: 0.9820200006943196
  brandStrength: 0.7741935
  brandColors:
    - '#DFD9CE'
    - '#9A9A91'
    - '#424440'
    - '#4A6D9B'
    - '#FC6C70'
  rhythmicContrast: 0.2585869440808892
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Thanninger
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.13678
layout_spectrum: 0.80774
